# Generated by Django 4.2.2 on 2023-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='address'),
            preserve_default=False,
        ),
    ]
