# Generated by Django 4.2.2 on 2023-07-03 15:48

import blog.path_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.path_generator.post_image_upload),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.path_generator.profile_image_upload),
        ),
    ]
