# Generated by Django 4.2.2 on 2023-07-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_at']},
        ),
    ]
