# @format

version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./BlogBackend
    ports:
      - "8000:8000"
    volumes:
      - ./BlogBackend:/app
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - BlogBackend/.env
    container_name: postgres_db
    image: postgres:14-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - PGUSER=root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    build:
      context: ./BlogFront
    ports:
      - 4000:80
    depends_on:
      - backend
    volumes:
      - ./BlogFront:/app

volumes:
  media:
  static:
