# @format

version: "3.9"

services:
  backend:
    build:
      context: ./BlogBackend
    ports:
      - "8080:8000"
    volumes:
      - ./BlogBackend:/app

    command: ./entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media:
  static:
