# Generated by Django 4.2.2 on 2023-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_write_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='write_email',
            new_name='writer_email',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='write_name',
            new_name='writer_name',
        ),
    ]
