# Generated by Django 4.2.2 on 2023-07-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_comments_create_at_comments_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-create_at']},
        ),
    ]
